// Diff the production platform surface against the devcontainer's, into index/drift.md.
//
// FSM-App runs three different Frappe/ERPNext pins (see its CLAUDE.md § Version pins).
// Production and CI are on frappe 16.31.0 / erpnext 16.32.1; the devcontainer is on 16.20.0,
// deliberately behind. That gap is where "works on my machine" lives: a DocType or method
// present locally but absent in production (or vice versa) fails only after deploy.
//
// Run after `sync-source.sh --with-devcontainer`.

import { readFile, writeFile } from "node:fs/promises";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(ROOT, "source");
const APPS = ["frappe", "erpnext"];
const pins = JSON.parse(await readFile(path.join(ROOT, "pins.json"), "utf8"));

for (const app of APPS) {
  if (!existsSync(path.join(SOURCE, ".devcontainer", app))) {
    console.error(`missing source/.devcontainer/${app} - run ./scripts/sync-source.sh --with-devcontainer first`);
    process.exit(1);
  }
}

function walk(dir, out = []) {
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    if (e.name === ".git" || e.name === "node_modules" || e.name === "__pycache__") continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

// Deliberately a coarser surface than build-index.mjs: names only. Drift is about "does this
// exist now", not field-level detail - that is what describe_doctype at the pin is for.
function surfaceOf(root) {
  const files = walk(root);
  const doctypes = new Map();
  const methods = new Set();
  const hooks = new Set();
  for (const full of files) {
    const rel = path.relative(root, full);
    if (full.endsWith(".json") && rel.includes(`${path.sep}doctype${path.sep}`)) {
      try {
        const def = JSON.parse(readFileSync(full, "utf8"));
        if (def?.doctype === "DocType" && def.name) doctypes.set(def.name, def.module ?? "");
      } catch { /* malformed json upstream is not our problem */ }
    } else if (full.endsWith(".py")) {
      const text = readFileSync(full, "utf8");
      const lines = text.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (/^@frappe\.whitelist\(/.test(lines[i])) {
          const d = /^\s*def\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(lines[i + 1] ?? "");
          if (d) methods.add(`${rel.replace(/\.py$/, "").split(path.sep).join(".")}.${d[1]}`);
        }
      }
      for (const m of text.matchAll(/get_hooks\(\s*(?:hook\s*=\s*)?["']([a-zA-Z_][a-zA-Z0-9_]*)["']/g)) hooks.add(m[1]);
    }
  }
  return { doctypes, methods, hooks };
}

// Both Sets and Maps are compared by key, so spread the keys explicitly — spreading a Map
// yields [key, value] pairs, which .has() never matches.
const diff = (a, b) => [...b.keys()].filter((x) => !a.has(x)).sort();

const lines = [
  "# Drift — production vs devcontainer",
  "",
  "> Generated by `scripts/build-drift.mjs`. **`index/` and `grep_source` describe production**,",
  "> which is what shipped code runs against. This file describes only how the *devcontainer*",
  "> differs from it — the gap where \"works on my machine\" hides.",
  "",
  "> A DocType or method listed as *absent in the devcontainer* still exists in production, so",
  "> building against it is correct; it just cannot be exercised locally until the devcontainer",
  "> is bumped. One listed as *absent in production* is the dangerous direction: local code that",
  "> passes dev and fails after deploy.",
  "",
  `Built ${new Date().toISOString().slice(0, 10)}.`,
  "",
  "| App | Production + CI (authoritative) | Devcontainer (local dev) |",
  "| --- | --- | --- |",
  ...APPS.map((a) => `| ${a} | \`${pins.source[a].tag}\` | \`${pins.devcontainer[a].tag}\` |`),
  "",
];

for (const app of APPS) {
  const prod = surfaceOf(path.join(SOURCE, app));
  const dev = surfaceOf(path.join(SOURCE, ".devcontainer", app));

  // "missing locally" = in production but not the devcontainer; "extra locally" is the
  // dangerous direction - present in dev, absent from what we actually deploy onto.
  const missingLocally = diff(dev.doctypes, prod.doctypes);
  const extraLocally = diff(prod.doctypes, dev.doctypes);
  const missingM = diff(dev.methods, prod.methods);
  const extraM = diff(prod.methods, dev.methods);
  const missingH = diff(dev.hooks, prod.hooks);
  const extraH = diff(prod.hooks, dev.hooks);

  lines.push(`## ${app} — production \`${pins.source[app].tag}\` vs devcontainer \`${pins.devcontainer[app].tag}\``, "");
  lines.push(
    `- DocTypes: ${prod.doctypes.size} in production, ${dev.doctypes.size} in the devcontainer (${missingLocally.length} not testable locally, ${extraLocally.length} local-only)`,
    `- Whitelisted methods: ${prod.methods.size} vs ${dev.methods.size} (${missingM.length} not testable locally, ${extraM.length} local-only)`,
    `- Hook keys: ${prod.hooks.size} vs ${dev.hooks.size} (${missingH.length} not testable locally, ${extraH.length} local-only)`,
    "",
  );

  const section = (title, items, note) => {
    if (!items.length) return;
    lines.push(`### ${title}`, "");
    if (note) lines.push(note, "");
    for (const i of items.slice(0, 200)) lines.push(`- \`${i}\``);
    if (items.length > 200) lines.push(`- …and ${items.length - 200} more`);
    lines.push("");
  };

  section(
    "DocTypes in production but not the devcontainer", missingLocally,
    "Safe to build against — they exist where we deploy. Just not reproducible locally until the devcontainer is bumped.",
  );
  section(
    "DocTypes in the devcontainer but NOT production", extraLocally,
    "**Dangerous.** Code written against these passes local dev and fails after deploy.",
  );
  section("Hook keys in production but not the devcontainer", missingH);
  section(
    "Hook keys in the devcontainer but NOT production", extraH,
    "**A hook registered against one of these silently never fires in production.**",
  );
  section("Whitelisted methods in production but not the devcontainer", missingM);
  section(
    "Whitelisted methods in the devcontainer but NOT production", extraM,
    "**Callers of these break after deploy.**",
  );
}

await writeFile(path.join(ROOT, "index", "drift.md"), lines.join("\n") + "\n");
console.error(`wrote index/drift.md (${lines.length} lines)`);
